**Contoh Kode Program KNN tanpa library Scikit-Learn**

In [2]:
import numpy as np
import matplotlib.pyplot as plt

X_train = np.array([
    [158,64],
    [170,86],
    [183,84],
    [191,80],
    [155,49],
    [163,59],
    [180,67],
    [158,54],
    [170,67]
])

y_train = ['male', 'male', 'male', 'male', 'female', 'female', 'female', 'female', 'female']

X_test = np.array([[155,70]])

In [5]:
# calculate euclidean distance
dis = np.sqrt(np.sum((X_train-X_test)**2, axis=1))
dis

array([ 6.70820393, 21.9317122 , 31.30495168, 37.36308338, 21.        ,
       13.60147051, 25.17935662, 16.2788206 , 15.29705854])

In [6]:
nn_sort = dis.argsort()[:3]
print(nn_sort)

nn_gender = np.take(y_train, nn_sort)
print(nn_gender)

from collections import Counter
b = Counter(np.take(y_train, dis.argsort()[:3]))
b.most_common(1)[0][0]

[0 5 8]
['male' 'female' 'female']


'female'

**Contoh Kode Program KNN menggunakan library Scikit-Learn**

In [9]:
from sklearn.preprocessing import LabelBinarizer
from sklearn.neighbors import KNeighborsClassifier

lb = LabelBinarizer()
y_trainbin = lb.fit_transform(y_train)
print(y_trainbin)

k=3
clf = KNeighborsClassifier(n_neighbors=k)
clf.fit(X_train, y_trainbin.reshape(-1))
pred_bin = clf.predict(np.array([X_test]).reshape(1,-1))[0]
pred_label = lb.inverse_transform(pred_bin)
print(pred_label)

[[1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]]
['female']


In [10]:
from sklearn.preprocessing import LabelBinarizer
from sklearn.neighbors import KNeighborsClassifier
X_test = np.array([[168,65],
                   [190,96],
                   [160,52],
                   [169,67]
                   ])
y_test = ['male', 'male', 'female', 'female']

# lb = LabelBinarizer()
y_testbin = lb.transform(y_test)
print('label biners:%s' %y_testbin.T[0])

k=3
clf = KNeighborsClassifier(n_neighbors=k)
clf.fit(X_train, y_trainbin.reshape(-1))
pred_bin = clf.predict(X_test)
pred_label = lb.inverse_transform(pred_bin)
print(pred_label)

label biners:[1 1 0 0]
['female' 'male' 'female' 'female']


In [11]:
from sklearn.metrics import accuracy_score
print('akurasi: %s' % accuracy_score(y_testbin, pred_bin))

akurasi: 0.75


In [12]:
from sklearn.metrics import precision_score
print('presisi: %s' % precision_score(y_testbin, pred_bin))

presisi: 1.0


In [13]:
from sklearn.metrics import recall_score
print('recall: %s' % recall_score(y_testbin, pred_bin))

recall: 0.5


**Contoh implementasi Regresi menggunakan algoritma KNN**

In [16]:
import numpy as np
import matplotlib.pyplot as plt

X_train = np.array([
    [158,1],
    [170,1],
    [183,1],
    [191,1],
    [155,0],
    [163,0],
    [180,0],
    [158,0],
    [178,0]
])

y_train = [64,66,84,80,49,59,67,54,77]

X_test = np.array([[168,1],
                   [170,1],
                   [160,0],
                   [169,0]
                   ])

y_test = [65,61,52,67]

In [18]:
from sklearn.preprocessing import LabelBinarizer
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error

k=3
clf = KNeighborsRegressor(n_neighbors=k)
clf.fit(X_train, y_train)
predictions = clf.predict(X_test)
print('prediksi : %s' % predictions)
print('MAE : %s' % mean_absolute_error(y_test, predictions))
print('SE : %s' % mean_squared_error(y_test, predictions))

prediksi : [63.         67.33333333 59.         67.33333333]
MAE : 3.9166666666666643
SE : 23.305555555555543
