In [1]:
#Tanpa Menggunakan library scikit-learn
import numpy as np
import matplotlib.pyplot as plt

X_train = np.array([
    [26 ,8],
    [26, 11],
    [29, 8],
    [34, 10],
    [36, 11],
    [33, 8],
    [30, 9],
    [27, 10],
    [27, 11],
    [26, 11],
    [31, 13],
    [34, 8],
])

y_train = ['Go out', 'Go out', 'Go out', 'Stay at home','Stay at home', 'Go out', 'Go out', 'Go out', 'Go out', 'Go out', 'Stay at home','Go out']

X_test = np.array([[30,10]])

In [4]:
# calculate euclidean distance
dis = np.sqrt(np.sum((X_train-X_test)**2, axis=1))
dis

array([4.47213595, 4.12310563, 2.23606798, 4.        , 6.08276253,
       3.60555128, 1.        , 3.        , 3.16227766, 4.12310563,
       3.16227766, 4.47213595])

In [5]:
dis = np.sqrt(np.sum((X_train-X_test)**2, axis=1))
print(dis)

nn_sort = dis.argsort()[:3]
print(nn_sort)
nn_gender = np.take(y_train,nn_sort)
print(nn_gender)


from collections import Counter
b = Counter(np.take(y_train,dis.argsort()[:3]))
b.most_common(1)[0][0]

[4.47213595 4.12310563 2.23606798 4.         6.08276253 3.60555128
 1.         3.         3.16227766 4.12310563 3.16227766 4.47213595]
[6 2 7]
['Go out' 'Go out' 'Go out']


'Go out'

In [6]:
# Menggunakan library scikit-learn
from sklearn.preprocessing import LabelBinarizer
from sklearn.neighbors import KNeighborsClassifier

lb = LabelBinarizer()
y_trainbin = lb.fit_transform(y_train)
print(y_trainbin)

k = 3
clf = KNeighborsClassifier(n_neighbors=k)
clf.fit(X_train, y_trainbin.reshape(-1))
pred_bin = clf.predict(np.array([X_test]).reshape(1, -1))[0]
pred_label = lb.inverse_transform(pred_bin)
print(pred_label)

[[0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]]
['Go out']


In [7]:
from sklearn.preprocessing import LabelBinarizer
from sklearn.neighbors import KNeighborsClassifier

X_test = np.array([
    [30, 10],
    [28, 13],
    [29, 9],
    [31, 12],
    [27, 8]
])

y_test = ['Stay at home', 'Go out', 'Go out', 'Stay at home', 'Go out']

# lb=LabelBinarizer()
y_testbin = lb.transform(y_test)
print('\nLabel Biner : %s' % y_testbin.T[0])

k = 3
clf = KNeighborsClassifier(n_neighbors=k)
clf.fit(X_train, y_trainbin.reshape(-1))
pred_bin = clf.predict(X_test)
pred_label = lb.inverse_transform(pred_bin)
print(pred_label)


Label Biner : [1 0 0 1 0]
['Go out' 'Go out' 'Go out' 'Stay at home' 'Go out']


In [9]:
from sklearn.metrics import accuracy_score
print('akurasi: %s' % accuracy_score(y_testbin,pred_bin))

akurasi: 0.8


In [10]:
from sklearn.metrics import precision_score
print('presisi: %s' % precision_score(y_testbin,pred_bin))

presisi: 1.0


In [11]:
from sklearn.metrics import recall_score
print('recall: %s' % recall_score(y_testbin,pred_bin))

recall: 0.5


In [16]:
# Evaluasi Regresi
import numpy as np
import matplotlib.pyplot as plt

X_train = np.array([
                    [26,1],
                    [26,1],
                    [29,1],
                    [34,0],
                    [36,0],
                    [33,1],
                    [30,1],
                    [27,1],
                    [27,1],
                    [26,1],
                    [31,0],
                    [34,1]
                ])

y_train=[8,11,8,10,11,8,9,10,11,11,13,8]

X_test = np.array([[30,0],
                   [28,1],
                   [29,1],
                   [31,0],
                   [27,1]
])

y_test=[10,13,9,12,8]

In [17]:
from sklearn.neighbors import KNeighborsRegressor

k=3
clf = KNeighborsRegressor(n_neighbors=k)
clf.fit(X_train,y_train)
predictions=clf.predict(X_test)
print('prediksi : %s' %predictions)

prediksi : [10.          9.66666667  9.         10.         10.66666667]


In [18]:
from sklearn.preprocessing import LabelBinarizer
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error
k=3
clf = KNeighborsRegressor(n_neighbors=k)
clf.fit(X_train,y_train)
predictions=clf.predict(X_test)
print('prediksi : %s' %predictions)
print('MAE : %s' %mean_absolute_error(y_test,predictions))
print('MSE : %s' %mean_squared_error(y_test,predictions))

prediksi : [10.          9.66666667  9.         10.         10.66666667]
MAE : 1.6
MSE : 4.444444444444445
